# Site Variables
title: Jason Howie
author: Jason Howie
description: Jason Howie's personal website
url: 'https://jasonrhowie.com'
baseurl: ''
# Permalink for blog posts
permalink: /blog/:year/:month/:title/

# Collections for portfolio
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-paginate-v2


# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: /:num/
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 3
    after: 3